language: objective-c
osx_image: xcode6.4
before_install:
- gem install xcpretty --no-document
script:
- set -o pipefail
- xcodebuild -project CLIKit.xcodeproj -scheme CLIKit -sdk macosx test | xcpretty -c
