language: objective-c
osx_image: xcode6.4
before_install:
- gem install xcpretty --no-document
script:
- set -o pipefail
- xcodebuild -project CommandKit.xcodeproj -scheme CommandKit -sdk macosx test | xcpretty -c
